### ISSUE TITLE
Renaming does not apply to equipped spectre

### ISSUE THREAD

**Issue by NarZook** [LlemonDuck/easy-pharaoh-sceptre#1]
![Sceptre](https://user-images.githubusercontent.com/45111338/167252512-2780b5ae-84b5-4383-abff-2165d8616e09.png)

**Comment by LlemonDuck** [comment]
This is intended and expressly forbidden by Jagex's [third party clients statement](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1).

**Comment by SandroVA** [comment]
I don't believe this is against TOS anymore. According to their newly updated guidelines.

https://secure.runescape.com/m=news/third-party-client-guidelines?oldschool=1

**Comment by LlemonDuck** [comment]
Yes with the updated guidelines I have already added it to the plugin. It should already be an option on your version. Please note also that I renamed the plugin to "Easy Teleports", if you are looking for it in your plugin list.

If it is not working on the equipment screen for you, please let me know.
